### ISSUE TITLE
spec errors?

### ISSUE THREAD

**Issue by reubenson** [learn-co-curriculum/flatiron-bnb-methods#7]
1) In neighborhood_spec.rb  around line 19
expect(@nabe1.neighborhood_openings('2014-05-01', '2014-05-30')).to include(@listing1)      
should be 
expect(@nabe1.neighborhood_openings('2014-05-01', '2014-05-30')).not_to include(@listing1) 
because @listing1 has a reservation that conflicts with the input dates.

2) In neighborhood_spec.rb around line 32
expect(Neighborhood.most_res).to eq(Neighborhood.find_by(:name => "Lakewood"))
should be 
expect(Neighborhood.highest_ratio_res_to_listings).to eq(Neighborhood.find_by(:name => "Lakewood"))
because Neighborhood.most_res is also identically run on line 42 

3) In city_spec.rb around line 15
expect(City.first.city_openings('2014-05-01', '2014-05-05')).to include(@listing1) 
should be 
expect(City.first.city_openings('2014-05-01', '2014-05-05')).to include(@listing2)
because @listing1 has a reservation that conflicts with the input dates, and @listing2 does not. similar error to (1) above.

**Comment by jmburges** [comment]
fixed! thank you

**Comment by JVThomas** [comment]
I think the original test was actually correct for city_spec.rb

Start of range for the test: 2014-05-01 = May 1st 2014
End of range for test: 2014-05-05 = May 5th 2014

Date Conversion is such due to format of dates as given in seeds.rb. Look at line 41, you'll see the checkout date stated as 2014-06-30, thus dates are in year-month-day format.

With that out of the way, @listing1 has an available reservation,
   id: 4
   checkin: Fri, 02 May 2014,
   checkout: Thu, 08 May 2014 

...and @listing2, with only one reservation total, does not...
   id: 2,
  checkin: Mon, 10 Mar 2014,
  checkout: Tue, 25 Mar 2014.

Also, @listing3 has no reservations (only listings with id = 1, 2, or 4 have reservations), so either give it a valid reservation or remove it from the spec.
